services:
  - type: web
    name: bonshop
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_EMAIL
        value: akklanh84@gmail.com
      - key: ADMIN_PASSWORD
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: KEYADMIN_SECRET
        value: huongdev8386
      - key: API_SECRET
        generateValue: true
      - key: PUBLIC_URL
        value: https://bonshop.onrender.com
      - key: PGSSL
        value: "true"
